core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<slug>', views.ProductDetailView.as_view(), name='product-detail'),
    path('terms-of-service/', views.TermsView.as_view(),name='terms'),
    path('privacy-policy/',views.PrivacyView.as_view(),name='privacy'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('webhooks', views.webhook_view),
]

fsp_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from core import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('faq/', views.FAQView.as_view(), name='faq'),
    path('', include('core.urls')),
    path('',include('users.urls')),
    path('', include('documentation.urls')),
    path('settings/',include('settings.urls')),
    url('^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

app_name = 'settings'

urlpatterns = [
    path('create-content/<page>/<type>',views.CreateContentView.as_view(),name='create-content'),
    path('update-content/<pk>',views.UpdateContentView.as_view(),name='update-content'),
    path('delete-content/<pk>',views.DeleteContentView.as_view(),name='delete-content'),
    path('add-image/<type>',views.CreateImageView.as_view(),name='add-image'),
    path('update-image/<pk>',views.UpdateImageView.as_view(),name='update-image'),
    path('delete-image/<pk>',views.DeleteImageView.as_view(),name='delete-image'),
    path('icons/',views.IconView.as_view(),name='icons'),
    path('themes/',views.ThemeView.as_view(),name='themes'),
    path('add-theme/<type>',views.CreateThemeView.as_view(),name='add-theme'),
    path('update-theme/<pk>',views.UpdateThemeView.as_view(),name='update-theme'),
    path('delete-theme/<pk>',views.DeleteThemeView.as_view(),name='delete-theme'),
    path('social-accounts/',views.SocialView.as_view(),name='socials'),
    path('add-social/<type>',views.CreateSocialView.as_view(),name='add-social'),
    path('update-social/<pk>',views.UpdateSocialView.as_view(),name='update-social'),
    path('delete-social/<pk>',views.DeleteSocialView.as_view(),name='delete-social'),
    path('optional-pages/',views.OptionalPageView.as_view(),name='pages'),
    path('add-page/<page>',views.CreateDisplayPageView.as_view(),name='add-page'),
    path('update-page/<pk>',views.UpdateDisplayPageView.as_view(),name='update-page'),
]

users/urls.py
from django.urls import path
from .views import LoginView,ProfileView, AccountSetUpView, activate, confirm_email, OrderDetailView, UpdateOrderView,CheckInboxView, InvalidLinkView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('profile/<pk>',ProfileView.as_view(), name='profile'),
    path('order/<pk>', OrderDetailView.as_view(), name='order-detail'),
    path('update-order/<pk>', UpdateOrderView.as_view(), name='update-order'),
    path('create-account/', AccountSetUpView.as_view(), name='set-password'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('confirm_email/<orderid>', confirm_email, name='confirm-email'),
    path('check-your-inbox/', CheckInboxView.as_view(), name='check-inbox'),
    path('invalid-link/', InvalidLinkView.as_view(), name='invalid-link'),
    path('activate/<orderidb64>/<token>', activate, name='activate'),

]

core/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from django.core.validators import MinValueValidator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site

import os

User = get_user_model()

class Product(models.Model):
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(unique=True,editable=False,null=True,blank=True)
    includes_setup = models.BooleanField(default=False,
        help_text = "Product includes deployment & hosting setup.")
    stripe_id = models.CharField(max_length=100,blank=True,
        help_text = "The product's Stripe Price ID")
    zip_file = models.FileField(upload_to='product_files',null=True)
    description = models.TextField(null=True,blank=True)
    additional_details = models.TextField(null=True,blank=True)
    keywords = models.CharField(max_length=250,blank=True, null=True)
    featured = models.BooleanField(default=False,
        help_text = "Display product on the homepage")
    archived = models.BooleanField(default=False,
        help_text = "Hide product from all listings to prevent new subscribers while keeping current ones.")

    def __str__(self):
        return str(self.title)

    def save(self, *args,**kwargs):
        self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse("core:product-detail", kwargs={'slug': self.slug})

    def filename(self):
        return os.path.basename(self.zip_file.name)

class ProductImage(models.Model):
    TYPE_CHOICES = [
        ('IMG', "Image"),
        ('VID', "Video"),
    ]
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    type = models.CharField(choices=TYPE_CHOICES, max_length=3)
    image = models.ImageField(upload_to='product_images', blank=True, null=True)
    video_embed_url = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{self.product.title} | {self.type}"

class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,null=True,on_delete=models.SET_NULL)
    order_date = models.DateTimeField(auto_now=True,editable=False)
    email = models.EmailField(max_length=254,blank=True, null=True,
        help_text="This email will be used to create your PythonAnywhere host account.")
    confirmed_email = models.BooleanField(default=False)
    business_name = models.CharField(max_length=100,blank=True, null=True,
        help_text="The name of your business/website.")
    host_username = models.CharField(max_length=100,blank=True, null=True)
    host_temporary_password = models.CharField(max_length=250,blank=True, null=True)
    setup_complete = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.user.email)
    def get_absolute_url(self):
        return reverse("users:order-detail", kwargs={'pk': self.pk})

core/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.core import mail
from mimetypes import guess_type

from django.template.loader import render_to_string
from django.contrib.auth import get_user_model
from settings import models as setting_models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from . import models

User = get_user_model()

import stripe
import os

stripe.api_key = settings.STRIPE_SECRET_KEY

def download(request, path):
    file_path=settings.MEDIA_ROOT / path
    if os.path.exists(file_path):
        with open(file_path,'rb') as fh:
            response=HttpResponse(fh.read(),content_type='application/zip')
            response['Content-Disposition']='attachment;filename='+os.path.basename(file_path)
            return response
    raise HttpResponse(status=404)

class IndexView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if models.Product.objects.all():
            products = models.Product.objects.all()
        else:
            products = ''

        # seo data
        try:
            seo=setting_models.Seo.objects.get(page='HOME')
        except ObjectDoesNotExist:
            seo=''

    # image & content data
        # Main Background Image
        try:
            main=setting_models.Image.objects.get(type='MAIN')
        except ObjectDoesNotExist:
            main=''

        # h1 block content
        if setting_models.Content.objects.filter(page='HOME'):
            content = True
            try:
                h1=setting_models.Content.objects.filter(type='H1',page='HOME').first()
            except ObjectDoesNotExist:
                h1=''
            try:
                h2=setting_models.Content.objects.filter(type='H2',page='HOME').first()
            except ObjectDoesNotExist:
                h2=''
        else:
            content = ''
            h1=''
            h2=''

        context = {
            'featured_products': models.Product.objects.filter(featured=True, archived=False)[0:],
            'seo': seo,
            'products': products,
            'content':content,
            'main':main,
            'h1':h1,
            'h2':h2,
        }
        return context

class AboutView(TemplateView):
    template_name = 'core/about.html'

    def get(self,*args,**kwargs):
        try:
            display=setting_models.DisplayPage.objects.get(page='ABOUT',display=True)
        except ObjectDoesNotExist:
            display=False

        if not display:
            return redirect('/')
        else:
            context = super().get(self.request,**kwargs)

            # seo data
            try:
                seo=setting_models.Seo.objects.get(page='ABOUT')
            except ObjectDoesNotExist:
                seo=''

                # image & content data
            # Main Background Image
            try:
                about_image =setting_models.Image.objects.get(type='ABOUT')
            except ObjectDoesNotExist:
                about_image=''

            # h1 block content
            if setting_models.Content.objects.filter(page='ABOUT'):
                content = True
            else:
                content = ''

            try:
                h1=setting_models.Content.objects.get(type='H1',page='ABOUT')
            except ObjectDoesNotExist:
                h1=''

            context = {
                'seo': seo,
                'content':content,
                'about_image':about_image,
                'h1':h1,
            }
            return render(self.request,'core/about.html',context)

class FAQView(TemplateView):
    template_name = 'core/faq.html'

    def get(self,*args,**kwargs):
        try:
            display=setting_models.DisplayPage.objects.get(page='FAQ',display=True)
        except ObjectDoesNotExist:
            display=False

        if not display:
            return redirect('/')
        else:
            context = super().get(self.request,**kwargs)

            # seo data
            try:
                seo=setting_models.Seo.objects.get(page='FAQ')
            except ObjectDoesNotExist:
                seo=''

        # image & content data
            # Main Background Image
            try:
                faq_image=setting_models.Image.objects.get(type='FAQ')
            except ObjectDoesNotExist:
                faq_image=''

            # h1 block content
            if setting_models.Content.objects.filter(page='FAQ'):
                content = True
            else:
                content = ''

            try:
                h1=setting_models.Content.objects.get(type='H1',page='FAQ')
            except ObjectDoesNotExist:
                h1=''

            context = {
                'seo': seo,
                'content':content,
                'faq_image':faq_image,
                'h1':h1,
                'h2':setting_models.Content.objects.filter(page='FAQ',type='H2')[0:],
            }
            return render(self.request,'core/faq.html',context)

class ProductListView(ListView):
    model = models.Product
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if setting_models.Content.objects.filter(page='LIST'):
            content = True
        else:
            content = ''
        try:
            h1=setting_models.Content.objects.filter(type='H1',page='LIST').first()
        except ObjectDoesNotExist:
            h1=''
        # seo data
        try:
            seo=setting_models.Seo.objects.get(page='LIST')
        except ObjectDoesNotExist:
            seo=''

        context = {
            'products': models.Product.objects.filter(archived=False)[0:],
            'content': content,
            'h1':h1,
            'seo':seo,
        }
        return context

class ProductDetailView(DetailView):
    model = models.Product
    context_object_name = 'product'

    def get_context_data(self, *args,**kwargs):
        context = super(ProductDetailView,self).get_context_data(*args,**kwargs)

        add_variables = {
            'stripe_publishable_key': settings.STRIPE_PUBLISHABLE_KEY,
            'cancel_url': settings.CANCEL_URL,
            'success_url': settings.SUCCESS_URL,
        }
        context.update(add_variables)
        return context

class TermsView(TemplateView):
    template_name = 'core/terms.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            h1=setting_models.Content.objects.get(type='H1',page='TERMS')
        except ObjectDoesNotExist:
            h1=''
        context = {
            'h1':h1,
        }
        return context

class PrivacyView(TemplateView):
    template_name = 'core/privacy.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            h1=setting_models.Content.objects.get(type='H1',page='PRIVACY')
        except ObjectDoesNotExist:
            h1=''
        context = {
            'h1':h1,
        }
        return context

class SuccessView(TemplateView):
    template_name = 'core/success.html'

@require_POST
@csrf_exempt
def webhook_view(request):
    payload=request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(payload,sig_header, settings.STRIPE_SIGNING_SECRET)
    except ValueError as e:
        # Invalid payload
        print(e)
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        print(e)
        return HttpResponse(status=400)

    # Handle a completed checkout
    if event['type'] == 'checkout.session.completed':
        #set variables
        order = event['data']['object']
        line_items = stripe.checkout.Session.list_line_items(order['id'], limit=5)
        price_id = line_items['data'][0]['price']['id']

        try:
            product = models.Product.objects.get(stripe_id=price_id)
            email = order['customer_details']['email']

            # Check if user exists
            if User.objects.filter(email=email).exists():
                user=User.objects.get(email=email)
            # create new user
            else:
                user = User.objects.create_user(
                    email=email,
                    password = None,
                )
                user.save()

            # create new order
            new_order = models.Order.objects.create(
                user=user,
                product=product,
            )
            new_order.save()

        except ObjectDoesNotExist:
            print("Purchased Product Does Not Exist")


    return HttpResponse(status=200)

templates/core/about.html
{% extends "base.html" %}
{% load static %}

{% block meta_block %}
  <title>{{seo.title}}</title>
  <meta name="description" property=og:description content="{{seo.description}}">
  <meta name="keywords" content="{{seo.keywords}}">
  <meta property="og:title" content="{{seo.title}}">
  <meta property="og:url" content="{% url 'about' %}">
{% endblock meta_block %}


{% block content %}

<div class="container py-4">

<div class="text-center">
  {% if content %}
  {% if h1 %}
    <div class="Jumbotron pt-4">
      {% if request.user.is_superuser %}
        <a class="float-right ml-4" style="color:black;" href="{% url 'settings:delete-content' pk=h1.pk %}?next={{ request.path|urlencode }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
        <a class="float-right"style="color:black;" href="{% url 'settings:update-content' pk=h1.pk %}?next={{ request.path|urlencode }}">
            <i class="fas fa-pencil-alt"></i>
        </a>
        <br>
      {% endif %}
      <p class="display-4">{{h1.heading}}</p>
    </div>
    <div class="text-center">
      <p class="lead">{{h1.details|linebreaks}}</p>
    </div>
    {% if about_image %}
      <img style="width:20em;"class="img-fluid card mx-auto" src="{{about_image.image.url}}" alt="About Image">
      {% if request.user.is_superuser %}
        <br>
        <a style="color:black;" href="{% url 'settings:update-image' pk=about_image.pk %}?next={{ request.path|urlencode }}">
            <i class="fas fa-pencil-alt"></i>
        </a>
        <a class="ml-4" style="color:black;" href="{% url 'settings:delete-image' pk=about_image.pk %}?next={{ request.path|urlencode }}"><i class="fa fa-trash"></i></a>
      {% endif %}
    {% else %}
    {% if request.user.is_superuser %}
      <a href="{% url 'settings:add-image' type='ABOUT' %}?next={{ request.path|urlencode }}">
          <i style="color:black;"class="fas fa-plus mr-4"></i><small class="text-muted">Add Image</small>
      </a>
    {% endif %}
    {% endif %}

  {% endif %}

  {% else %}
  <div class="Jumbotron pt-4">
    {% if request.user.is_superuser %}
    <div class="text-center">
      <a class="float-right" style="color:black;" href="{% url 'settings:create-content' page='ABOUT' type='H1' %}?next={{ request.path|urlencode }}"><i class="fas fa-pencil-alt"></i></a>
      <br>
    </div>
    {% endif %}
    <p class="display-4">About</p>
  </div>
  <div class="text-center">
    <p class="lead">Tell us about your business! </p>
    <p class="card-text">How were you founded? Who dreamed the great idea?</p>
    <p class="card-text">Click the pencil to enter your content!</p>

    <img style="width:20em;"class="img-fluid card mx-auto" src="{% static "img/Default_Background.png" %}" alt="Default About Image">
  </div>


  {% endif %}
</div>
</div>


{% endblock content %}

templates/core/check_your_email.html
{% extends "base.html" %}
{% load static %}
{% block meta_block %}
{% endblock meta_block %}


{% block content %}

<div class="mb-5 pb-5">
  <div class="jumbotron text-center">
    <h1 class="display-4">Confirmation Email Sent</h1>
    <p class="lead">Please check your inbox for the confirmation email and click on the activation link.</p>
  </div>
</div>

{% endblock content %}

templates/core/faq.html
{% extends "base.html" %}
{% load static %}

{% block meta_block %}
  <title>{{seo.title}}</title>
  <meta name="description" property=og:description content="{{seo.description}}">
  <meta name="keywords" content="{{seo.keywords}}">
  <meta property="og:title" content="{{seo.title}}">
  <meta property="og:url" content="{% url 'faq' %}">
{% endblock meta_block %}


{% block content %}

<div class="container pt-5">

<div class="mb-5 pb-5">
    <div class="row">
      <div class="col-lg-10 col-md-6 mx-auto">
        <div class="card mb-4 pb-4">
          <div class="card-header">
    {% if h1 %}
            {% if request.user.is_superuser %}
              <a class="float-right ml-4" style="color:black;" href="{% url 'settings:delete-content' pk=h1.pk %}?next={{ request.path|urlencode }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
              <a class="float-right"style="color:black;" href="{% url 'settings:update-content' pk=h1.pk %}?next={{ request.path|urlencode }}">
                  <i class="fas fa-pencil-alt"></i>
              </a>
              <br>
            {% endif %}
            <p class="card-title display-4 text-center">{{h1.heading}}</p>
            <small class="text-center">{{h1.details|linebreaks}}</small>
          </div>
    {% else %}
        {% if request.user.is_superuser %}
          <a class="float-right mr-4"style="color:black;" href="{% url 'settings:create-content' page='FAQ' type='H1' %}?next={{ request.path|urlencode }}">
              <i class="fas fa-pencil-alt"></i>
          </a>
          <br>
        {% endif %}
        <p class="card-title display-4 text-center">Welcome to the FAQ page!</p>
      </div>
    {% endif %}
        <div class="card-body">
          <ul class="list-group list-group-flush">
          {% if h2 %}
          {% for q in h2 %}
            <li class="list-group-item">
              {% if request.user.is_superuser %}
                <a class="float-right ml-4" style="color:black;" href="{% url 'settings:delete-content' pk=q.pk %}?next={{ request.path|urlencode }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                <a class="float-right"style="color:black;" href="{% url 'settings:update-content' pk=q.pk %}?next={{ request.path|urlencode }}">
                    <i class="fas fa-pencil-alt"></i>
                </a>
                <br>
              {% endif %}
              <p class="card-title pt-2 h3">{{q.heading}}</p>
              <p class="card-text">{{q.details|linebreaks}}</p>
            </li>
          {% endfor %}
          {% if request.user.is_superuser %}
          <div class="text-center">
            <a class="float-right" style="color:black;" href="{% url 'settings:create-content' page='FAQ' type='H2' %}?next={{ request.path|urlencode }}"><i class="fas fa-plus"></i></a>
            <br>
          </div>
          {% endif %}

    {% else %}
    <li class="list-group-item">
      {% if request.user.is_superuser %}
        <a class="float-right"style="color:black;" href="{% url 'settings:create-content' page='FAQ' type='H2' %}?next={{ request.path|urlencode }}">
            <i class="fas fa-plus"></i>
        </a>
        <br>
      {% endif %}
      <p class="card-title h3">Want to add a question?</p>
      <p class="card-text lead">Click the plus sign to get started!</p>
    </li>
    {% endif %}
    </ul>
  </div>
        </div>
      </div>
    </div>


</div>
</div>


{% endblock content %}

templates/core/features.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
  <p class="display-4 my-5 pt-5 text-center">Choose Your Featured Image</p>
  <div class="row">

    <div class="col-lg-4 col-xl-4 ml-xl-4 mb-4">
      <p class="lead">Convey what's important about your business with a high quality image</p>
    </div>
    <!-- image-->
    <div class="col-lg-7 col-xl-7 mb-4 float-right">
        <img src="{% static "img/Snips/Display.PNG" %}" class="img-fluid card-img-top shadow-sm"

          alt="Where's the picture?">
    </div>


  </div>

</div>

{% endblock content%}

templates/core/privacy.html
{% extends "base.html" %}
{% load static %}

{% block meta_block %}
  <title>Terms of Service</title>
{% endblock meta_block %}


{% block content %}

<div class="container py-4">

<div class="text-center">
  {% if h1 %}
    <div class="Jumbotron pt-4">
      {% if request.user.is_superuser %}
        <a class="float-right ml-4" style="color:black;" href="{% url 'settings:delete-content' pk=h1.pk %}?next={{ request.path|urlencode }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
        <a class="float-right"style="color:black;" href="{% url 'settings:update-content' pk=h1.pk %}?next={{ request.path|urlencode }}">
            <i class="fas fa-pencil-alt"></i>
        </a>
        <br>
      {% endif %}

      <h1>{{h1.heading}}</h1>
    </div>
    <div class="text-center">
      <p class="card-text">{{h1.details|linebreaks}}</p>
      <p class="card-text">{{h1.additional_details|linebreaks}}</p>
    </div>

  {% else %}
  <div class="mb-b pb-5">

  <div class="Jumbotron py-4">
    <h1>Privacy Policy</h1>
  </div>
  <div class="text-center pb-5 mb-5">
    <p class="card-text pb-2">A Privacy Policy is required for this website.</p>
    <p class="card-text pb-2">You can add your policy by clicking the button below and pasting your legal jargon in the details field.</p>
    {% if request.user.is_superuser %}
    <a class="btn btn-outline-dark" href="{% url 'settings:create-content' page='PRIVACY' type='H1' %}?next={{ request.path|urlencode }}">Get Started</a>
    {% endif %}

  </div>
</div>
  {% endif %}
</div>
</div>


{% endblock content %}

templates/core/product_list.html
{% extends "base.html" %}
{% load static %}

{% block meta_block %}
  <title>{{seo.title}}</title>
  <meta name="description" property=og:description content="{{seo.description}}">
  <meta name="keywords" content="{{seo.keywords}}">
  <meta property="og:title" content="{{seo.title}}">
  <meta property="og:url" content="{% url 'core:product-list' %}">
{% endblock meta_block %}


{% block content %}

<div class="container pt-5">

<div class="text-center">
  <div class="Jumbotron pb-2">
    {% if content %}
      {% if request.user.is_superuser %}
      <a class="float-right ml-4" style="color:black;" href="{% url 'settings:delete-content' pk=h1.pk %}?next={{ request.path|urlencode }}"><i class="fa fa-trash"></i></a>
      <a class="float-right"style="color:black;" href="{% url 'settings:update-content' pk=h1.pk %}?next={{ request.path|urlencode }}">
        <i class="fas fa-pencil-alt"></i>
      </a>
      <br>
      {% endif %}

    <p class="display-4">{{h1.heading}}</p>
    <p class="lead">{{h1.details}}</p>
    {% else %}
      {% if request.user.is_superuser %}
      <div class="text-center">
        <a class="float-right" style="color:black;" href="{% url 'settings:create-content' page='LIST' type='H1' %}?next={{ request.path|urlencode }}"><i class="fas fa-pencil-alt"></i></a>
        <br>
      </div>
      {% endif %}

      <p class="display-4">All Products</p>
      <p class="lead">Browse all our products!</p>
    {% endif %}
  </div>

  <hr>

  <div class="row my-4 py-4">
  {% for product in products %}
      <div class="col-lg-4 col-md-6 mb-4 mx-auto">
        <div class="card shadow">
          <!--Product Image/Video-->
          {% if product.images.all.0 %}
            {% if product.images.all.0.type == 'IMG' %}
              <!--Image-->
              <img src="{{product.images.all.0.image.url}}" class="img-fluid card-img-top shadow-sm" alt="{{product.title}}">
            {% else %}
            <!--Video-->
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item card-img-top shadow-sm"src="{{product.images.all.0.video_embed_url}}"></iframe>
            </div>
            {% endif %}
          {% else %}
          <!--Default Blank Product Image-->
            <img src="{% static "img/Default_Blank_Product.png" %}" class="img-fluid card-img-top shadow-sm" alt="{{product.title}}">
          {% endif %}

            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title">{{product.title}}</h4>
                <!--Text-->
                <p class="card-text">{{product.description|linebreaks|safe}}</p>
                <a href="{% url 'core:product-detail' slug=product.slug %}"
                  class="btn btn-block btn-outline-dark shadow-sm btn-md">Details
                </a>
            </div>
        </div>
    </div>
  {% endfor %}

  </div>
</div>
</div>


{% endblock content %}

templates/core/terms.html
{% extends "base.html" %}
{% load static %}

{% block meta_block %}
  <title>Terms of Service</title>
{% endblock meta_block %}


{% block content %}

<div class="container py-4">

<div class="text-center">
  {% if h1 %}
    <div class="Jumbotron pt-4">
      {% if request.user.is_superuser %}
        <a class="float-right ml-4" style="color:black;" href="{% url 'settings:delete-content' pk=h1.pk %}?next={{ request.path|urlencode }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
        <a class="float-right"style="color:black;" href="{% url 'settings:update-content' pk=h1.pk %}?next={{ request.path|urlencode }}">
            <i class="fas fa-pencil-alt"></i>
        </a>
        <br>
      {% endif %}
      <h1>{{h1.heading}}</h1>
    </div>
    <div class="text-center">
      <p class="card-text">{{h1.details|linebreaks}}</p>
      <p class="card-text">{{h1.additional_details|linebreaks}}</p>
    </div>

  {% else %}
  <div class="mb-b pb-5">

  <div class="Jumbotron py-4">
    <h1>Terms of Service</h1>
  </div>
  <div class="text-center pb-5 mb-5">
    <p class="card-text pb-2">Terms of Service are required for this website.</p>
    <p class="card-text pb-2">You can add your terms by clicking the button below and pasting your legal jargon in the details field.</p>
    {% if request.user.is_superuser %}
    <a class="btn btn-outline-dark" href="{% url 'settings:create-content' page='TERMS' type='H1' %}?next={{ request.path|urlencode }}">Get Started</a>
    {% endif %}
  </div>
</div>
  {% endif %}
</div>
</div>


{% endblock content %}