core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<slug>', views.ProductDetailView.as_view(), name='product-detail'),
    path('terms-of-service/', views.TermsView.as_view(),name='terms'),
    path('privacy-policy/',views.PrivacyView.as_view(),name='privacy'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('webhooks', views.webhook_view),
]

fsp_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from core import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('faq/', views.FAQView.as_view(), name='faq'),
    path('', include('core.urls')),
    path('',include('users.urls')),
    path('', include('documentation.urls')),
    path('settings/',include('settings.urls')),
    url('^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

app_name = 'settings'

urlpatterns = [
    path('create-content/<page>/<type>',views.CreateContentView.as_view(),name='create-content'),
    path('update-content/<pk>',views.UpdateContentView.as_view(),name='update-content'),
    path('delete-content/<pk>',views.DeleteContentView.as_view(),name='delete-content'),
    path('add-image/<type>',views.CreateImageView.as_view(),name='add-image'),
    path('update-image/<pk>',views.UpdateImageView.as_view(),name='update-image'),
    path('delete-image/<pk>',views.DeleteImageView.as_view(),name='delete-image'),
    path('icons/',views.IconView.as_view(),name='icons'),
    path('themes/',views.ThemeView.as_view(),name='themes'),
    path('add-theme/<type>',views.CreateThemeView.as_view(),name='add-theme'),
    path('update-theme/<pk>',views.UpdateThemeView.as_view(),name='update-theme'),
    path('delete-theme/<pk>',views.DeleteThemeView.as_view(),name='delete-theme'),
    path('social-accounts/',views.SocialView.as_view(),name='socials'),
    path('add-social/<type>',views.CreateSocialView.as_view(),name='add-social'),
    path('update-social/<pk>',views.UpdateSocialView.as_view(),name='update-social'),
    path('delete-social/<pk>',views.DeleteSocialView.as_view(),name='delete-social'),
    path('optional-pages/',views.OptionalPageView.as_view(),name='pages'),
    path('add-page/<page>',views.CreateDisplayPageView.as_view(),name='add-page'),
    path('update-page/<pk>',views.UpdateDisplayPageView.as_view(),name='update-page'),
]

settings/models.py
from django.db import models

# Create your models here.
class DisplayPage(models.Model):
    DISPLAY_PAGE_CHOICES = [
        ('ABOUT' , 'About Page'),
        ('FAQ' , 'FAQ'),
    ]

    page = models.CharField(
        max_length=7,
        choices=DISPLAY_PAGE_CHOICES,
    )
    navbar_label = models.CharField(max_length=50,null=True,blank=True)
    display = models.BooleanField(default=True)

    def __str__(self):
        return self.page

class Social(models.Model):
    SOCIAL_TYPE_CHOICES = [
        ('FB','Facebook'),
        ('IG','Instagram'),
        ('PIN','Pinterest'),
        ('TW','Twitter'),

    ]
    type = models.CharField(
        max_length=3,
        choices=SOCIAL_TYPE_CHOICES,
        default='FB',
        unique=True
    )
    link = models.URLField(max_length=200,blank=True,null=True)
    display = models.BooleanField(default=True)

    def __str__(self):
        return self.type


class Content(models.Model):
    CONTENT_PAGE_CHOICES = [
        ('HOME' , 'Home Page'),
        ('ABOUT' , 'About Page'),
        ('FAQ' , 'FAQ'),
        ('LIST' , 'Product List Page'),
        ('TERMS','Terms of Service'),
        ('PRIVACY','Privacy Policy'),
    ]
    CONTENT_TYPE_CHOICES = [
        ('H1' , 'Heading 1'),
        ('H2' , 'Heading 2'),
    ]

    page = models.CharField(
        max_length=7,
        choices=CONTENT_PAGE_CHOICES,
        default='HOME'
    )
    type = models.CharField(
        max_length=2,
        choices=CONTENT_TYPE_CHOICES,
        default='H1'
    )
    heading = models.CharField(max_length=254)
    details = models.TextField(blank=True,null=True,
        help_text = "Add some details as a paragraph under the heading")

    class Meta:
        verbose_name_plural = "Website Content"

    def __str__(self):
        return f"{self.page} | {self.type}"

class Image(models.Model):
    IMAGE_TYPE_CHOICES = [
        ('MAIN',"Main Homepage Image"),
        ('ABOUT',"About Page Image"),
        ('ICON','Site Icon'),
        ('A_ICON','Apple Icon'),
        ('LOGO','Navbar Logo'),

    ]
    type = models.CharField(
        max_length=6,
        choices=IMAGE_TYPE_CHOICES,
        default='MAIN',
        unique = True
    )
    image = models.ImageField(upload_to='website_images',null=True)
    alt = models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return self.type

class Seo(models.Model):
    PAGE_CHOICES = [
        ('HOME' , 'Home Page'),
        ('ABOUT' , 'About Page'),
        ('FAQ' , 'FAQ'),
        ('LIST','Product List Page'),
    ]
    page = models.CharField(
        max_length=7,
        choices=PAGE_CHOICES,
        default='HOME',
        unique=True,
    )
    title = models.CharField(max_length=50,blank=True,null=True,
        help_text = "This will display on the browser tab")
    description = models.CharField(max_length=250,blank=True,null=True,
        help_text = "This will display a text preview in internet search results")
    keywords = models.TextField(blank=True,null=True,
        help_text = "Enter keywords separated by a comma. (Example: subscription website, affordable)")
    #TODO: add social url, title, img, & description

    class Meta:
        verbose_name_plural = "SEO"

    def __str__(self):
        return self.page

class Theme(models.Model):
    TYPE_CHOICES = [
        ('NAVBAR', 'Navbar'),
        ('FOOTER','Footer'),
    ]
    TEXT_COLOR_CHOICES = [
        ('LIGHT', 'light'),
        ('DARK','dark'),
    ]

    type = models.CharField(max_length=6,choices=TYPE_CHOICES, unique=True)
    text_color = models.CharField(max_length=5,choices=TEXT_COLOR_CHOICES)
    background_color = models.CharField(max_length=20,
        help_text='Enter a valid hex code. (Example: #301934)')

    def __str__(self):
        return self.type

settings/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from . import models


class IconView(LoginRequiredMixin, TemplateView):
    template_name = 'settings/set_icons.html'
class ThemeView(LoginRequiredMixin, TemplateView):
    template_name = 'settings/set_themes.html'
class SocialView(LoginRequiredMixin, TemplateView):
    template_name = 'settings/set_social.html'
class OptionalPageView(LoginRequiredMixin, TemplateView):
    template_name = 'settings/set_pages.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        page_list = ['ABOUT','FAQ']

        for var in page_list:
            try:
                globals()[var] = models.DisplayPage.objects.get(page=var)
            except ObjectDoesNotExist:
                globals()[var] = ''
        context = {
            'about':ABOUT,
            'faq':FAQ,
        }

        return context

class CreateContentView(LoginRequiredMixin, CreateView):
    model=models.Content
    fields=['heading','details']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

    def form_valid(self, form):
        form.instance.page=self.kwargs['page']
        form.instance.type=self.kwargs['type']
        return super(CreateContentView, self).form_valid(form)

class UpdateContentView(LoginRequiredMixin, UpdateView):
    model=models.Content
    fields=['heading','details']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class DeleteContentView(LoginRequiredMixin, DeleteView):
    model=models.Content

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class CreateImageView(LoginRequiredMixin, CreateView):
    model=models.Image
    fields = ['image','alt']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

    def form_valid(self, form):
        form.instance.type=self.kwargs['type']
        return super(CreateImageView, self).form_valid(form)

class UpdateImageView(LoginRequiredMixin, UpdateView):
    model=models.Image
    fields = ['image','alt']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class DeleteImageView(LoginRequiredMixin, DeleteView):
    model=models.Image

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class CreateThemeView(LoginRequiredMixin, CreateView):
    model=models.Theme
    fields=['text_color','background_color']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

    def form_valid(self, form):
        form.instance.type=self.kwargs['type']
        return super(CreateThemeView, self).form_valid(form)

class UpdateThemeView(LoginRequiredMixin, UpdateView):
    model=models.Theme
    fields=['text_color','background_color']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class DeleteThemeView(LoginRequiredMixin, DeleteView):
    model=models.Theme

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class CreateSocialView(LoginRequiredMixin, CreateView):
    model=models.Social
    fields=['link']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

    def get_context_data(self,*args,**kwargs):
        context = super(CreateSocialView,self).get_context_data(*args,**kwargs)
        add_variables = {
            'type':self.kwargs['type']
        }
        context.update(add_variables)
        return context

    def form_valid(self, form):
        form.instance.type=self.kwargs['type']
        return super(CreateSocialView, self).form_valid(form)

class UpdateSocialView(LoginRequiredMixin, UpdateView):
    model=models.Social
    fields=['link','display']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class DeleteSocialView(LoginRequiredMixin, DeleteView):
    model=models.Social

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

class CreateDisplayPageView(LoginRequiredMixin, CreateView):
    model=models.DisplayPage
    template_name = 'settings/display_page_form.html'
    fields=['navbar_label','display']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

    def get_context_data(self,*args,**kwargs):
        context = super(CreateDisplayPageView,self).get_context_data(*args,**kwargs)
        add_variables = {
            'page':self.kwargs['page']
        }
        context.update(add_variables)
        return context

    def form_valid(self, form):
        form.instance.page=self.kwargs['page']
        return super(CreateDisplayPageView, self).form_valid(form)

class UpdateDisplayPageView(LoginRequiredMixin, UpdateView):
    model=models.DisplayPage
    template_name = 'settings/display_page_form.html'
    fields=['navbar_label','display']

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse('core:index')

templates/settings/content_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5 my-5">
  <div class="col-md-8 mx-auto">
    <form class="uniForm" method="post">
      {% csrf_token %}
      <div class="text-center pb-4">
        <h1 class="pb-4">Are you sure you want to delete this text block?</h1>
        <div class="card">
          <div class="card-body">
            <h3 class="card-heading">{{ object.heading }}</h3>
            <p class="card-text">{{ object.details }}</p>
          </div>
        </div>
      </div>

      {{form|crispy}}
      <div class="text-center">
        <a class="btn btn-outline-dark" href="{% url 'core:index' %}">No Thanks</a>
        <button class="btn btn-danger" type="submit">Delete</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/settings/content_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5 my-5">
  <div class="col-md-8 mx-auto">
    <form class="uniForm" method="post">
      {% csrf_token %}
      {{form|crispy}}
      <button class="btn btn-primary" type="submit">Save</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/settings/display_page_form.html
{% extends "settings/settings_base.html" %}
{% load crispy_forms_tags %}

{% block setting_content %}
    <form class="uniForm" method="post">
      <h5>{{ page }}</h5>
      {% csrf_token %}
      {{form|crispy}}
      <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock setting_content %}

templates/settings/image_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5 my-5">
  <div class="col-md-8 mx-auto">
    <form class="uniForm" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      <div class="text-center pb-4">
        <h1 class="pb-4">Are you sure you want to delete this image?</h1>
            <img style="width:20em;"class="img-fluid card mx-auto"src="{{ object.image.url }}" alt="{{ object.alt }}">
      </div>

      {{form|crispy}}
      <div class="text-center">
        <a class="btn btn-outline-dark" href="{% url 'core:index' %}">No Thanks</a>
        <button class="btn btn-danger" type="submit">Delete</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/settings/image_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5 my-5">
  <div class="card col-md-8 mx-auto">
    <div class="card-body">
      <form class="uniForm" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Save</button>
      </form>
  </div>
  </div>
</div>
{% endblock content %}

templates/settings/set_icons.html
{% extends "settings/settings_base.html" %}
{% block setting_content %}
  <h5 class="card-title text-center mb-4">Website Icons</h5>
  <p>Navbar Logo:
    {% if logo %}
    <img style="height:1.7em;"src="{{logo.image.url}}"alt="{{logo.alt}}">
      <a href="{% url 'settings:update-image' pk=logo.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
      <a href="{% url 'settings:delete-image' pk=logo.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    </p>

    {% else %}
      <a href="{% url 'settings:add-image' type='LOGO' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

  <p>Site Icon:
    {% if site_icon %}
    <img style="height:1.7em;"src="{{site_icon.image.url}}"alt="{{logo.alt}}">
      <a href="{% url 'settings:update-image' pk=site_icon.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
      <a href="{% url 'settings:delete-image' pk=site_icon.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    </p>

    {% else %}
      <a href="{% url 'settings:add-image' type='ICON' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

  <p>Apple-Touch Icon:
    {% if apple_icon %}
    <img style="height:1.7em;"src="{{apple_icon.image.url}}"alt="{{logo.alt}}">
      <a href="{% url 'settings:update-image' pk=apple_icon.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
      <a href="{% url 'settings:delete-image' pk=apple_icon.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    </p>

    {% else %}
      <a href="{% url 'settings:add-image' type='A_ICON' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

{% endblock setting_content %}

templates/settings/set_pages.html
{% extends "settings/settings_base.html" %}
{% block setting_content %}
  <h5 class="card-title text-center mb-4">Optional Pages</h5>
  <p><strong>About Page:</strong>
  {% if about %}
    <a href="{% url 'settings:update-page' pk=about.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <br>
    <small>Navbar Label: {{about.navbar_label}}</small>
    <br>
    <small>Display: {% if about.display %}Yes{% else %}No{% endif %}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-page' page='ABOUT' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

  <p><strong>FAQ Page:</strong>
  {% if faq %}
    <a href="{% url 'settings:update-page' pk=faq.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <br>
    <small>Navbar Label: {{faq.navbar_label}}</small>
    <br>
    <small>Display: {% if faq.display %}Yes{% else %}No{% endif %}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-page' page='FAQ' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}


{% endblock setting_content %}

templates/settings/set_social.html
{% extends "settings/settings_base.html" %}
{% block setting_content %}
  <h5 class="card-title text-center mb-4">Social Accounts</h5>
  <p><strong>Facebook:</strong>
  {% if facebook %}
    <a href="{% url 'settings:update-social' pk=facebook.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <a href="{% url 'settings:delete-social' pk=facebook.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    <br>
    <small>Link: {{facebook.link}}</small>
    <br>
    <small>Display: {{facebook.display}}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-social' type='FB' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

  <p><strong>Instagram:</strong>
  {% if insta %}
    <a href="{% url 'settings:update-social' pk=insta.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <a href="{% url 'settings:delete-social' pk=insta.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    <br>
    <small>Link: {{insta.link}}</small>
    <br>
    <small>Display: {{insta.display}}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-social' type='IG' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

  <p><strong>Pinterest:</strong>
  {% if pinterest %}
    <a href="{% url 'settings:update-social' pk=pinterest.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <a href="{% url 'settings:delete-social' pk=pinterest.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    <br>
    <small>Link: {{pinterest.link}}</small>
    <br>
    <small>Display: {{pinterest.display}}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-social' type='PIN' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

  <p><strong>Twitter:</strong>
  {% if twitter %}
    <a href="{% url 'settings:update-social' pk=twitter.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <a href="{% url 'settings:delete-social' pk=twitter.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    <br>
    <small>Link: {{twitter.link}}</small>
    <br>
    <small>Display: {{twitter.display}}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-social' type='TW' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}




{% endblock setting_content %}

templates/settings/set_themes.html
{% extends "settings/settings_base.html" %}
{% block setting_content %}
  <h5 class="card-title text-center mb-4">Website Theme</h5>
  <p><strong>Navbar Theme:</strong>
  {% if nav %}
    <a href="{% url 'settings:update-theme' pk=nav.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <a href="{% url 'settings:delete-theme' pk=nav.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    <br>
    <small>Text Color: {{nav_text}}</small>
    <br>
    <small>Background Color: {{nav.background_color}}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-theme' type='NAVBAR' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

  <p><strong>Footer Theme:</strong>
  {% if footer %}
    <a href="{% url 'settings:update-theme' pk=footer.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fas fa-pencil-alt"></i></a>
    <a href="{% url 'settings:delete-theme' pk=footer.pk %}?next={{ request.path|urlencode }}"><i class="float-right ml-4 fa fa-trash"></i></a>
    <br>
    <small>Text Color: {{footer_text}}</small>
    <br>
    <small>Background Color: {{footer.background_color}}</small>
    </p>

  {% else %}
      <a href="{% url 'settings:add-theme' type='FOOTER' %}?next={{ request.path|urlencode }}"><i class="float-right fas fa-plus"></i></a>
  {% endif %}

{% endblock setting_content %}

templates/settings/settings_base.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5 my-5">
  <div class="col-md-10 mx-auto">
    <div class="card pb-5">
      <div class="card-header text-center">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'settings:icons' %}">Icons</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'settings:themes' %}">Themes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'settings:socials' %}">Social Accounts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'settings:pages' %}">Optional Pages</a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        {% block setting_content %}

        {% endblock setting_content %}
      </div>
    </div>

  </div>
</div>
{% endblock content %}

templates/settings/social_confirm_delete.html
{% extends "settings/settings_base.html" %}
{% load crispy_forms_tags %}

{% block setting_content %}
    <form class="uniForm" method="post">
      {% csrf_token %}
      <div class="text-center pb-4">
        <h5 class="pb-4">Are you sure you want to delete this social account link?</h5>
        <p>{{object}}</p>
      </div>

      {{form|crispy}}
      <div class="text-center">
        <a class="btn btn-outline-dark" href="{% url 'core:index' %}">No Thanks</a>
        <button class="btn btn-danger" type="submit">Delete</button>
      </div>
    </form>
{% endblock setting_content %}

templates/settings/social_form.html
{% extends "settings/settings_base.html" %}
{% load crispy_forms_tags %}

{% block setting_content %}
    <form class="uniForm" method="post">
      <h5>{{ type }}</h5>
      {% csrf_token %}
      {{form|crispy}}
      <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock setting_content %}

templates/settings/theme_confirm_delete.html
{% extends "settings/settings_base.html" %}
{% load crispy_forms_tags %}

{% block setting_content %}
    <form class="uniForm" method="post">
      {% csrf_token %}
      <div class="text-center pb-4">
        <h5 class="pb-4">Are you sure you want to delete this theme?</h5>
        <p>{{object}}</p>
      </div>

      {{form|crispy}}
      <div class="text-center">
        <a class="btn btn-outline-dark" href="{% url 'core:index' %}">No Thanks</a>
        <button class="btn btn-danger" type="submit">Delete</button>
      </div>
    </form>
{% endblock setting_content %}

templates/settings/theme_form.html
{% extends "settings/settings_base.html" %}
{% load crispy_forms_tags %}

{% block setting_content %}
    <form class="uniForm" method="post">
      {% csrf_token %}
      {{form|crispy}}
      <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock setting_content %}