core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<slug>', views.ProductDetailView.as_view(), name='product-detail'),
    path('terms-of-service/', views.TermsView.as_view(),name='terms'),
    path('privacy-policy/',views.PrivacyView.as_view(),name='privacy'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('webhooks', views.webhook_view),
]

fsp_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from core import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('faq/', views.FAQView.as_view(), name='faq'),
    path('', include('core.urls')),
    path('',include('users.urls')),
    path('', include('documentation.urls')),
    path('settings/',include('settings.urls')),
    url('^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

app_name = 'settings'

urlpatterns = [
    path('create-content/<page>/<type>',views.CreateContentView.as_view(),name='create-content'),
    path('update-content/<pk>',views.UpdateContentView.as_view(),name='update-content'),
    path('delete-content/<pk>',views.DeleteContentView.as_view(),name='delete-content'),
    path('add-image/<type>',views.CreateImageView.as_view(),name='add-image'),
    path('update-image/<pk>',views.UpdateImageView.as_view(),name='update-image'),
    path('delete-image/<pk>',views.DeleteImageView.as_view(),name='delete-image'),
    path('icons/',views.IconView.as_view(),name='icons'),
    path('themes/',views.ThemeView.as_view(),name='themes'),
    path('add-theme/<type>',views.CreateThemeView.as_view(),name='add-theme'),
    path('update-theme/<pk>',views.UpdateThemeView.as_view(),name='update-theme'),
    path('delete-theme/<pk>',views.DeleteThemeView.as_view(),name='delete-theme'),
    path('social-accounts/',views.SocialView.as_view(),name='socials'),
    path('add-social/<type>',views.CreateSocialView.as_view(),name='add-social'),
    path('update-social/<pk>',views.UpdateSocialView.as_view(),name='update-social'),
    path('delete-social/<pk>',views.DeleteSocialView.as_view(),name='delete-social'),
    path('optional-pages/',views.OptionalPageView.as_view(),name='pages'),
    path('add-page/<page>',views.CreateDisplayPageView.as_view(),name='add-page'),
    path('update-page/<pk>',views.UpdateDisplayPageView.as_view(),name='update-page'),
]

users/urls.py
from django.urls import path
from .views import LoginView,ProfileView, AccountSetUpView, activate, confirm_email, OrderDetailView, UpdateOrderView,CheckInboxView, InvalidLinkView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('profile/<pk>',ProfileView.as_view(), name='profile'),
    path('order/<pk>', OrderDetailView.as_view(), name='order-detail'),
    path('update-order/<pk>', UpdateOrderView.as_view(), name='update-order'),
    path('create-account/', AccountSetUpView.as_view(), name='set-password'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('confirm_email/<orderid>', confirm_email, name='confirm-email'),
    path('check-your-inbox/', CheckInboxView.as_view(), name='check-inbox'),
    path('invalid-link/', InvalidLinkView.as_view(), name='invalid-link'),
    path('activate/<orderidb64>/<token>', activate, name='activate'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  {% block meta_block %}

  {% endblock meta_block %}

  <!-- Site Icon -->
  {% if site_icon %}
    <link rel="icon" href="{{site_icon.image.url}}">
  {% else %}
    <link rel="icon" href="{% static "img/Default_Logo.png" %}">
  {% endif %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static "css/master.css" %}?{% now "U" %}" rel="stylesheet">

  {% block extra_head %}

  {% endblock extra_head %}
</head>

<body>

  <!--Main Navigation-->
  <header>
    <!-- Navbar -->
    <nav class="navbar shadow fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
      <div class="container">
        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'core:index' %}">
          {% if logo %}
          <img style="height:1.7em;"
              src="{{logo.image.url}}"
              alt="">
          {% else %}
          <img style="height:1.7em;"
              src="{% static "img/Default_Navbar_Logo.png" %}"
              alt="WSS">

          {% endif %}
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'core:index' %}">Home</a>
            </li>

            {% for page in display_list %}
              <li class="nav-item">
                <a class="nav-link waves-effect"
                href="{% url page.page|lower %}" >{{page.navbar_label}}</a>
              </li>
            {% endfor %}

          </ul>

          <!-- Right -->
          <ul class="navbar-nav nav-flex-icons">

            {% if facebook.display %}
            <li class="nav-item">
              <a href="{{facebook.link}}" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            {% endif %}
            {% if twitter.display %}
            <li class="nav-item">
              <a href="{{twitter.link}}" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            {% endif %}
            {% if pinterest.display %}
            <li class="nav-item">
              <a href="{{pinterest.link}}" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-pinterest"></i>
              </a>
            </li>
            {% endif %}
            {% if insta.display %}
            <li class="nav-item">
              <a href="{{insta.link}}" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-instagram"></i>
              </a>
            </li>
            {% endif %}
            {% if request.user.is_superuser %}
            <li class="nav-item">
              <a href="{% url 'settings:icons' %}" class="nav-link waves-effect">
                <i class="fas fa-cog"></i>
              </a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link waves-effect mr-2"
              href="{% url 'users:profile' pk=request.user.pk %}" >Account</a>
            </li>
              {% if nav %}

              <li class="nav-item">
                <a class="nav-link waves-effect btn btn-outline-{{nav_text}}"
                href="{% url 'users:logout' %}" >Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link waves-effect btn btn-outline-dark"
                href="{% url 'users:logout' %}" >Logout</a>
              </li>
              {% endif %}
            {% else %}
              {% if nav %}
              <li class="nav-item">
                <a class="nav-link waves-effect btn btn-outline-{{nav_text}}"
                href="{% url 'users:login' %}" >Login</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link waves-effect btn btn-outline-dark"
                href="{% url 'users:login' %}" >Login</a>
              </li>
              {% endif %}

            {% endif %}

          </ul>

        </div>

      </div>
    </nav>
    <!-- Navbar -->

  </header>
  <!--Main Navigation-->

  <!--Main layout-->
  <main class="pb-4">
    {% block content %}

    {% endblock content %}
  </main>

  <!--Main layout-->

  <!--Footer-->
  {% if footer %}
    <footer style="background-color:{{footer.background_color}};"class="{{footer_text}}-footer-text text-center font-small mt-4 pb-4">
  {% else %}
    <footer style="background-color:black;"class="light-footer-text text-center mt-4 pb-4">
  {% endif %}
    {% block extra_footer %}

    {% endblock extra_footer %}

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-5">
          <div class="nav justify-content-center">

          {% if facebook.display %}
          <a href="{{facebook.link}}" class="nav-link waves-effect" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
          </a>
          {% endif %}
          {% if twitter.display %}
          <a href="{{twitter.link}}" class="nav-link waves-effect" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
          </a>
          {% endif %}
          {% if pinterest.display %}
          <a href="{{pinterest.link}}" class="nav-link waves-effect" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
          </a>
          {% endif %}
          {% if insta.display %}
          <a href="{{insta.link}}" class="nav-link waves-effect" target="_blank">
            <i class="fab fa-instagram mr-3"></i>
          </a>
          {% endif %}
      </div>

      <hr>
      <small><a class="mr-2"href="{% url 'core:terms' %}">Terms of Service</a></small>
      <small><a class="mr-2"href="{% url 'core:privacy' %}">Privacy Policy</a></small>
      <small><a class="mr-2"href="{% url 'admin:index' %}">Administration</a></small>
    </div>
    <!-- Social icons -->


  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>

  <!-- Initializations -->
  {% block extra_scripts %}

  {% endblock extra_scripts %}
</body>

</html>

templates/confirm_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
{% if success %}
{{ user.username }}, your account is confirmed!
{% else %}
Error, invalid token!
{% endif %}
</body>
</html>

templates/mail_body.html
{% autoescape off %}
Hello,
Please click on the link to confirm your email.
http://{{ domain }}{% url 'users:activate' orderidb64=orderid token=token %}
{% endautoescape %}