core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<slug>', views.ProductDetailView.as_view(), name='product-detail'),
    path('terms-of-service/', views.TermsView.as_view(),name='terms'),
    path('privacy-policy/',views.PrivacyView.as_view(),name='privacy'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('webhooks', views.webhook_view),
]

documentation/urls.py
from django.urls import path
from . import views

app_name = 'documentation'

urlpatterns = [
    path('deployment-guide/<slug>/',views.deployment_guide_view, name='deployment-guide'),
]

fsp_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from core import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('faq/', views.FAQView.as_view(), name='faq'),
    path('', include('core.urls')),
    path('',include('users.urls')),
    path('', include('documentation.urls')),
    path('settings/',include('settings.urls')),
    url('^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import LoginView,ProfileView, AccountSetUpView, activate, confirm_email, OrderDetailView, UpdateOrderView,CheckInboxView, InvalidLinkView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('profile/<pk>',ProfileView.as_view(), name='profile'),
    path('order/<pk>', OrderDetailView.as_view(), name='order-detail'),
    path('update-order/<pk>', UpdateOrderView.as_view(), name='update-order'),
    path('create-account/', AccountSetUpView.as_view(), name='set-password'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('confirm_email/<orderid>', confirm_email, name='confirm-email'),
    path('check-your-inbox/', CheckInboxView.as_view(), name='check-inbox'),
    path('invalid-link/', InvalidLinkView.as_view(), name='invalid-link'),
    path('activate/<orderidb64>/<token>', activate, name='activate'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _




# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # removes email from REQUIRED_FIELDS

    objects = UserManager()

    def __str__(self):
        return (self.email)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from django.contrib.auth.forms import AuthenticationForm, SetPasswordForm


class LoginForm(AuthenticationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_id = 'login-form'

class CreateAccountForm(SetPasswordForm):
    email = forms.EmailField(max_length=250, required=True, widget=forms.EmailInput())

    def __init__(self,*args,**kwargs):
        super().__init__(self,*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_id = 'set-password-form'

    def clean(self):
        cleaned_data = super().clean()
        email=cleaned_data.get('email')
        UserModel=get_user_model()

        if not UserModel.objects.filter(email=email).exists():
            print("email doesn't exist")
            msg="We don't have record of a purchase under that email. Please enter the email used at the time of purchase."
            self.add_error('email',msg)

        elif UserModel.objects.get(email=email).has_usable_password():
            msg="You already set your password. Please login to view or re-download your purchase."
            self.add_error('email',msg)
        return cleaned_data

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, UpdateView, DetailView, TemplateView
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404, render
from django.utils.translation import gettext as _
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseRedirect

from core.models import Order
from .forms import LoginForm, CreateAccountForm

import stripe
# Create your views here.

class LoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'pk': self.request.user.pk})

class AccountSetUpView(FormView):
    form_class=CreateAccountForm
    template_name='users/set_password.html'

    def get_success_url(self):
        pk = self.request.user.pk
        return reverse_lazy('users:profile',args=[pk])

    def form_valid(self,form):
        valid = super(AccountSetUpView, self).form_valid(form)
        email, password = form.cleaned_data.get('email'), form.cleaned_data.get('new_password1')

        #get user account & set password
        UserModel = get_user_model()
        user = UserModel.objects.get(email=email)
        user.set_password(password)
        user.save()

        #login user
        user = authenticate(email=email, password=password)
        login(self.request, user)
        send_email(user)

        return valid

class ProfileView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        user = self.request.user
        order_list = Order.objects.filter(user=user)
        context = {
            'user':user,
            'orders':order_list,
        }
        return render(self.request, 'users/profile.html', context)

class OrderDetailView(LoginRequiredMixin, DetailView):
    model=Order

def confirm_email(request, orderid):
    user = request.user
    order = Order.objects.get(pk=orderid)
    current_site = get_current_site(request)
    mail_subject = 'Confirm your Full Stack Pak Email'
    message = render_to_string('mail_body.html', {
        'user': user,
        'domain': current_site.domain,
        'orderid':urlsafe_base64_encode(force_bytes(orderid)),
        'token':account_activation_token.make_token(user),
    })
    to_email = order.email
    email = EmailMessage(
                mail_subject, message, to=[to_email]
    )
    email.send()
    return HttpResponseRedirect(reverse('users:check-inbox'))

class CheckInboxView(LoginRequiredMixin, TemplateView):
    template_name = 'core/check_your_email.html'

class InvalidLinkView(TemplateView):
    template_name = 'core/invalid_link.html'

def activate(request, orderidb64, token):
    try:
        order_id = force_text(urlsafe_base64_decode(orderidb64))
        order = Order.objects.get(pk=order_id)
    except:
        order = None
    if order is not None and order.user==request.user and account_activation_token.check_token(request.user, token):
        order.confirmed_email = True
        order.save()
        mail_subject = 'Order Ready for Setup'
        message = "Hello, the required infomation has been completed on an order, and it's now ready for setup. Please login to the Administration to view the order details."
        to_email = 'support@fullstackpak.com'
        email = EmailMessage(
            mail_subject, message, to=[to_email]
        )
        email.send()
        return HttpResponseRedirect(reverse('users:order-detail', args=[order_id]))
    else:
        return HttpResponseRedirect(reverse('users:invalid-link'))

class UpdateOrderView(LoginRequiredMixin, UpdateView):
    model=Order
    fields=['email', 'business_name']

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_block %}
{% endblock meta_block %}


{% block content %}
<main >

  <div class="">
    <div class="jumbotron">
      <h1 class="display-4 text-center">Login</h1>
    </div>
    <div class="container">

      <div class="col-md-8 mx-auto">
        <form method="POST">
          {% csrf_token %}
          {% crispy form %}
          <div class="text-center pb-4">
            <input type="submit"
            class="btn btn-primary btn-lg"
            value="Login">
            <a class="ml-2 btn btn-outline-dark"href="{% url 'password_reset' %}">Forgot Password</a>
          </div>
        </form>
        <hr>
        <div class="Jumbotron text-center py-2 ">

        <p class="lead">Logging in for the first time? Set your password here to securely access your purchase.</p>
        <div class="text-center lead">
          <a class="btn btn-outline-dark"href="{% url 'users:set-password' %}">Set Password</a>
        </div>
      </div>
      </div>
    </div>


  </div>
</main>







{% endblock content %}

templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% block meta_block %}
{% endblock meta_block %}


{% block content %}

<div class="mb-5 pb-5">
  <div class="jumbotron text-center">
    <h1 class="display-4">Your Purchases</h1>
    <p class="lead">{{user.email}}</p>
  </div>
  <div class="container pb-5">

  <div class="row">
  {% for order in orders %}
    <div class="col-lg-5 col-md-6 mb-4 mx-auto">
      <div class="card shadow">
        <!--Product Image/Video-->
        {% if order.product.images.all.0 %}
          {% if order.product.images.all.0.type == 'IMG' %}
            <!--Image-->
            <img src="{{order.product.images.all.0.image.url}}" class="img-fluid card-img-top shadow-sm" alt="{{order.product.title}}">
          {% else %}
          <!--Video-->
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item card-img-top shadow-sm"src="{{order.product.images.all.0.video_embed_url}}"></iframe>
          </div>
          {% endif %}
        {% else %}
        <!--Default Blank Product Image-->
          <img src="{% static "img/Default_Blank_Product.png" %}" class="img-fluid card-img-top shadow-sm" alt="{{order.product.title}}">
        {% endif %}
        <div class="card-body">
          <h3 class="card-title text-center">{{order.product.title}}</h3>
          <p class="card-text text-center">{{order.product.description}}</p>
          {% if order.product.includes_setup %}
            <a class="btn btn-block btn-primary btn-lg" href="{% url 'users:order-detail' pk=order.pk %}">Setup Details</a>
          {% else %}
            <a class="btn btn-block btn-primary btn-lg" href="{{order.product.zip_file.url}}" download="{{order.product.filename}}">Download</a>
            <a class="btn btn-block btn-outline-dark" href="{% url 'documentation:deployment-guide' order.product.slug %}">Deployment Guide</a>
          {% endif %}
        </div>
      </div>
      <br>
  </div>
  {% endfor %}
</div>
</div>
</div>

{% endblock content %}

templates/users/set_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_block %}
{% endblock meta_block %}


{% block content %}
<main >

    <div class="jumbotron text-center">
      <h1 class="display-4">Access Your Downloads</h1>
      <p class="lead">Set your password to securely retrieve your digital purchase.</p>
      <p>Unlimited Downloads | Return as many times as you want</p>

    </div>
    <div class="container">
      <div class="col-md-8 mx-auto">
        <form method="POST">
          {% csrf_token %}
          {% crispy form %}
          <div class="text-center my-4">
            <input class="btn btn-primary btn-lg"type="submit" value="Access My Purchase">
          </div>
        </form>
        <hr>
        <div class="Jumbotron text-center py-2 ">
          <p class="lead">Returning customer? Log in to retrieve your purchases.</p>
          <div class="text-center lead">
            <a class="btn btn-outline-dark"href="{% url 'users:login' %}">Login</a>
          </div>
        </div>
      </div>
  </div>
</main>
{% endblock content %}